<?php $form = $this->form; ?>
<div class="bs-docs-section">

    <div class="well">


        <?php
        $form->setAttribute('action', $this->url('admin/article',['action' => 'add']));
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        <fieldset>
            <legend>Add article</legend>

            <?php foreach ($form as $element):
                $attributes = $element->getAttributes();
                $label = $element->getLabel();
                if(!empty($label)){
                    $element->setLabelAttributes(['class' => 'col-lg-2 control-label' ]);
                    if(isset($attributes['required'])){
                        $element->setLabel($label . ' *');
                    }
                }

                ?>
                <div class="form-group">
                    <?php if(isset($attributes['type']) && 'text' == $attributes['type']):?>
                        <?php echo  $this->formLabel($element); ?>
                        <div class="col-lg-10">
                            <?php echo $this->formInput($element)?>
                        </div>

                    <?php elseif(isset($attributes['type']) && 'textarea' == $attributes['type']):?>
                        <?=  $this->formLabel($element); ?>

                        <div class="col-lg-10">
                            <?= $this->formTextArea($element); ?>
                        </div>

                    <?php elseif(isset($attributes['type']) && 'file' == $attributes['type']):?>

                        <?=  $this->formLabel($element) ?>

                        <div class="col-lg-10">
                            <?= $this->formFile($element) ?>
                        </div>

                    <?php elseif(isset($attributes['type']) && 'select' == $attributes['type']):?>

                        <?=  $this->formLabel($element) ?>

                        <div class="col-lg-10">
                            <?= $this->formSelect($element) ?>
                        </div>

                    <?php else: ?>
                        <div class="col-lg-10">
                            <?= $this->formRow($element) ?>
                        </div>
                    <?php endif ?>
                </div>
            <?php endforeach;?>
        </fieldset>

        <?php echo $this->form()->closeTag(); ?>
    </div>

</div>