version: '2'
services:
    mysql:
        image: mysql/mysql-server:5.6
        ports:
            - "3306:3306"
        volumes:
            - "./.data/db:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: mysql

    zend:
        build: .
        environment:
            XDEBUG_CONFIG: remote_host=192.168.1.4
        image: zend
        depends_on:
            - mysql
        ports:
            - "80:80"
        links:
            - mysql:mysql
        volumes:
            - "../:/var/www/site"
        restart: always