version: '2'
services:
    mysql-blog:
        image: mysql/mysql-server:5.6
        network_mode: "bridge"
        ports:
            - "3306:3306"
        volumes:
            - "./.data/db:/var/lib/mysql"
        restart: always
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: mysql

    zend-blog:
        build: .
        environment:
            XDEBUG_CONFIG: remote_host=192.168.1.13
        image: zend
        network_mode: "bridge"
        depends_on:
            - mysql-blog
        ports:
            - "80:80"
        links:
            - mysql-blog:mysql-blog
        volumes:
            - "../:/var/www/site"
        restart: always